In [1]:
test_input = '''30373
25512
65332
33549
35390'''

In [24]:
import requests

URL = "https://adventofcode.com/{year}/day/{day}/input"
url = URL.format(year='2022', day=8)
cookies = {"session":"53616c7465645f5fd345d8c12076a357c8d31b2c0c4ad1c152eefbd5c1cf09e0c8d6d7f657fc558887d443d2d07fbc90728ada9b6a91afcecb9926ffb4981a93"}
req = requests.get(url, cookies=cookies)

if req.status_code != 200:
    print("Error. Got status:", req.status_code)
    print(req.text)
    exit(3)
else:
    my_input = req.text

In [94]:
this_input = test_input

In [115]:
this_input = my_input

In [116]:
a = [ l for l in this_input.split("\n") if l != ""]
M= np.matrix([ [int(l[i]) for i in range(len(l))] for l in a])

In [117]:
M

matrix([[1, 1, 3, ..., 1, 0, 1],
        [3, 3, 2, ..., 2, 0, 0],
        [0, 1, 1, ..., 2, 1, 0],
        ...,
        [3, 0, 3, ..., 1, 0, 3],
        [3, 2, 2, ..., 2, 0, 3],
        [2, 1, 0, ..., 2, 1, 2]])

In [118]:
Visible = np.ones(M.shape)*-1
Visible

array([[-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       ...,
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.],
       [-1., -1., -1., ..., -1., -1., -1.]])

In [119]:
size_dim_0 = M.shape[0]
size_dim_1 = M.shape[1]

for i0 in range(size_dim_0) :
    for i1 in range(size_dim_1) :
        
#         print(i0,i1)
        
        if i0 == 0 or i0 == size_dim_0-1 or i1 == 0 or i1 == size_dim_1-1 :
            Visible[i0,i1] = 1
#             print("\t","edge",1)
        else :
            tree = M[i0,i1]
            if M[i0,:i1].max() < tree or \
                M[i0,i1+1:].max() < tree or \
                M[:i0,i1].max() < tree or \
                M[i0+1:,i1].max() < tree :
                    Visible[i0,i1] = 1
#                     print("\t",1)
            else :
                    Visible[i0,i1] = 0
#                     print("\t",0)
                    
                
                
                
        
        
        

In [120]:
Visible

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 0., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 0., 1., ..., 0., 0., 1.],
       [1., 1., 1., ..., 0., 0., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [121]:
Visible.sum()

1700.0

In [122]:
Score = np.ones(M.shape)*-1

In [123]:
size_dim_0 = M.shape[0]
size_dim_1 = M.shape[1]

for i0 in range(size_dim_0) :
    for i1 in range(size_dim_1) :
        
#         print(i0,i1)
        
        if i0 == 0 or i0 == size_dim_0-1 or i1 == 0 or i1 == size_dim_1-1 :
            Score[i0,i1] = 0
#             print("\t","edge")
            continue
        else :
            tree = M[i0,i1]
            test_stopview = M>=tree
            
            count_trees_0m = 0
            for i in range(i0-1,-1,-1):
                count_trees_0m += 1
                if test_stopview[i,i1] :
                    break
            count_trees_0p = 0
            for i in range(i0+1,size_dim_0):
                count_trees_0p += 1
                if test_stopview[i,i1] :
                    break
                    
            count_trees_1m = 0
            for i in range(i1-1,-1,-1):
                count_trees_1m += 1
                if test_stopview[i0,i] :
                    break
            count_trees_1p = 0
            for i in range(i1+1,size_dim_1):
                count_trees_1p += 1
                if test_stopview[i0,i] :
                    break
            
            Score[i0,i1] = count_trees_0m*count_trees_0p*count_trees_1m*count_trees_1p

In [124]:
Score

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0., 15., 12., ...,  2.,  1.,  0.],
       [ 0.,  1.,  2., ...,  2.,  2.,  0.],
       ...,
       [ 0.,  1., 16., ...,  2.,  1.,  0.],
       [ 0.,  5.,  3., ...,  4.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [125]:
Score.max()

470596.0